version: "3"
services:
  frontend:
    image: substance9/text2qti-web-frontend:latest
    container_name: text2qti-web-frontend
    ports:
      - 7553:80

  backend:
    image: substance9/text2qti-web-backend:latest
    restart: always
    container_name: backend
    expose:
      - 3001
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
